
try{
    throw(1);
}catch(err){
    print("error",err);
}